[package]
name = "tidy"
version = "0.2.0"
authors = ["William Dussault <dalloriam@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "libcond"
path = "src/libcond/lib.rs"

[[bin]]
name = "tidy"
path = "src/main.rs"

[dependencies]
anyhow = "1.0"
clap = "2.33.3"
ctrlc = "3.1.7"
nom = "5"
serde = { version = "1.0.116", features = ["derive"]}
serde_json = "1.0.59"
snafu = "0.6"
parse_duration = "2.1.0"
rood = "0.2"
shellexpand = "2.0.0"
walkdir = "2"
