[package]
name = "tidy"
version = "0.1.3"
authors = ["William Dussault <dalloriam@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "libcond"
path = "src/libcond/lib.rs"

[[bin]]
name = "tidy"
path = "src/main.rs"

[dependencies]
clap = "2.33.1"
ctrlc = "3.1.4"
logos = "~0"
serde = { version = "1.0.111", features = ["derive"]}
serde_json = "1.0.53"
parse_duration = "2.1.0"
rood = "0.1.1"
shellexpand = "2.0.0"
walkdir = "2"
