[package]
name = "tidy"
version = "0.1.0"
authors = ["William Dussault <dalloriam@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "libcond"
path = "src/libcond/lib.rs"

[[bin]]
name = "tidy"
path = "src/main.rs"

[dependencies]
logos = "~0"
serde = { version = "1.0.104", features = ["derive"]}
serde_json = "1.0.48"
parse_duration = "2.0.1"
rood = {path = "../rood"}
shellexpand = "1.1.1"
walkdir = "2"
