name = 'tidy'
version = '0.1.2'
stack = 'rust'
artifact_directory = 'artifacts'

[[build]]
architecture = 'amd64'
platform = 'linux'

[[artifact]]
name = 'tidy'
include_checksum = false
path_template = '$(BUILD)/tidy'
target_name_template = 'tidy-$(PLATFORM)-$(ARCHITECTURE)'
