name: Validate & Release
on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install latest stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Bootstrap Landlord
        run: |
          mkdir ~/bin
          sudo wget https://github.com/purposed/binman/releases/latest/download/binman-linux-amd64 -O /usr/local/bin/binman
          sudo chmod +x /usr/local/bin/binman
          binman install landlord
      - name: Landlord Release
        run: |
          ~/bin/landlord release
      - name: Release
        uses: docker://softprops/action-gh-release
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: artifacts/linux-amd64/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
