name: Test
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "v*"

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install latest stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Bootstrap Landlord
        run: |
          sudo wget https://github.com/purposed/binman/releases/download/v0.2.0/binman-linux-amd64 -O /usr/local/bin/binman
          sudo chmod +x /usr/local/bin/binman
          binman --version
          sudo binman install --dir /usr/local/bin landlord
      - name: Validate
        run: |
          landlord validate --mode release
          landlord validate --mode debug
